### ISSUE TITLE
Empty page at the end of full paper

### ISSUE THREAD

**Issue by raghavian** [MIDL-Conference/MIDLLatexTemplate#17] opened 2021-12-17 14:51 UTC
There seems to be some bug which renders an empty page at the end of a full paper. I think it only happens when there's an Appendix section. Could be related to the Bug #10.

**Comment by tvercaut** [comment] 2021-12-17 16:33
Could you post a minimal example to reproduce the issue?

**Comment by tvercaut** [comment] 2022-03-21 10:23
Closing due to lack of MWE

**Closed as completed by tvercaut** 2022-03-21 10:23 UTC
